name: Publish to NuGet

on:
    # push:
    #   branches:
    #     - main
    workflow_dispatch:  

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --configuration Release --no-restore

      - name: Pack Asb.Abstractions
        run: dotnet pack Asb.Abstractions/Asb.Abstractions.csproj --configuration Release --output ./artifacts

      - name: Pack Asb
        run: dotnet pack Asb/Asb.csproj --configuration Release --output ./artifacts

      - name: Push Asb.Abstractions to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./artifacts/Asb.Abstractions.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json

      - name: Push Asb to NuGet
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: dotnet nuget push ./artifacts/Asb.*.nupkg --api-key $NUGET_API_KEY --source https://api.nuget.org/v3/index.json
